---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: expressjs
  labels:
    app: expressjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expressjs
  template:
    metadata:
      labels:
        app: expressjs
    spec:
      containers:
      - name: expressjs
        image: geogtr/devopspractice:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-pass
              key: password
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: expressjs
spec:
  selector:
    app: expressjs
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysql-pv
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      containers:
      - name: mysql
        image: geogtr/mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-pass
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-pv
          mountPath: /var/lib/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: LoadBalancer


